function theme_fourseasdark()
    Theme(
        colormap = :turbo,
        strokewidth = 10.0,
        strokecolor = :white,
        strokevisible = true,
        font = fourseasfont(),
        backgroundcolor = darkbg,
        textcolor = :white,
        Axis = (
            backgroundcolor = darkbg,
            xgridcolor = :gray38,
            ygridcolor = :gray38,
            xminorgridcolor = :gray51,
            xminorgridvisible = true,
            yminorgridcolor = :gray51,
            yminorgridvisible = true,
            leftspinevisible = false,
            rightspinevisible = false,
            bottomspinevisible = false,
            topspinevisible = false,
            xminorticksvisible = false,
            yminorticksvisible = false,
            xticksvisible = false,
            yticksvisible = false,
            spinewidth = 1,
            xticklabelcolor = :white,
            yticklabelcolor = :white,
            titlecolor = :white,
            xticksize = 4,
            yticksize = 4,
            xtickwidth = 1.5,
            ytickwidth = 1.5,
            xgridwidth = 1.5,
            ygridwidth = 1.5,
            xlabelpadding = 3,
            ylabelpadding = 3,
            palette = (
                patchcolor = [      (cornflowerblue, 0.7),
                                    (crimson, 0.7),
                                    (cucumber, 0.7),
                                    (california, 0.7),
                                    (juliapurple, 0.7)],
                color = [           (cornflowerblue, 0.7),
                                    (crimson, 0.7),
                                    (cucumber, 0.7),
                                    (california, 0.7),
                                    (juliapurple, 0.7)]),
            titlefont = fourseasfont(), # "times serif bold",
            xticklabelfont = fourseasfont(),
            yticklabelfont = fourseasfont(),
            xlabelfont = fourseasfont(),
            ylabelfont = fourseasfont(),
            titlesize = 20,
        ),
        Legend = (
            framevisible = false,
            padding = (0, 0, 0, 0),
            patchcolor = :transparent,
            titlefont = fourseasfont(),
            labelfont = fourseasfont(),
        ),
        Axis3 = (
            backgroundcolor = darkbg,
            xgridcolor = :gray51,
            ygridcolor = :gray51,
            zgridcolor = :gray51,
            xspinesvisible = false,
            yspinesvisible = false,
            zspinesvisible = false,
            yzpanelcolor = darkbg,
            xzpanelcolor = darkbg,
            xypanelcolor = darkbg,
            xticksvisible = false,
            yticksvisible = false,
            zticksvisible = false,
            titlefont = fourseasfont(),
            xticklabelfont = fourseasfont(),
            yticklabelfont = fourseasfont(),
            zticklabelfont = fourseasfont(),
            xlabelfont = fourseasfont(),
            ylabelfont = fourseasfont(),
            zlabelfont = fourseasfont(),
            titlesize = 20,
        ),
        Colorbar = (
            tickcolor = :white,
            tickalign = 1,
            ticklabelcolor = :white,
            spinewidth = 0,
            ticklabelpad = 5,
            ticklabelfont = fourseasfont(),
            labelfont = fourseasfont(),
        ),
        Textbox = (
            font = fourseasfont(),
        )
    )
end
export theme_fourseasdark
